version: '3.7'
services: 
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    image: redis:6.0.4
    command: redis-server --requirepass ${REDIS_PWD}
    restart: unless-stopped
    ports:
      - 6379:6379
volumes:
  pgdata:
