name: deploy-prod

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create env file
      run: |
          touch .env
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
          echo SESSION_SECRET='${{ secrets.SESSION_SECRET }}' >> .env
          echo GRAPHQL_PATH='${{ secrets.GRAPHQL_PATH }}' >> .env
          echo APPLICATION_NAME='${{ secrets.APPLICATION_NAME }}' >> .env
          echo HOSTNAME='${{ secrets.HOSTNAME }}' >> .env

          echo POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' >> .env
          echo POSTGRES_USER='${{ secrets.POSTGRES_USER }}' >> .env
          echo POSTGRES_DB='${{ secrets.POSTGRES_DB }}' >> .env
          echo TYPEORM_URL='${{ secrets.TYPEORM_URL }}' >> .env

          echo REDIS_URL='${{ secrets.REDIS_URL }}' >> .env
          echo REDIS_PWD='${{ secrets.REDIS_PWD }}' >> .env

          echo LASTFM_API_KEY='${{ secrets.LASTFM_API_KEY }}' >> .env
          echo YOUTUBE_API_KEY='${{ secrets.YOUTUBE_API_KEY }}' >> .env
          echo AUDIODB_API_KEY=${{ secrets.AUDIODB_API_KEY }} >> .env

          echo TZ=${{ secrets.TZ }} >> .env
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        overwrite: true
        source: "."
        target: "/home/api.spectrefm.com"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd /home/api.spectrefm.com &&  sudo chmod u+x deploy.sh && ./deploy.sh production